networks:
  local-network:
    driver: bridge

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: products
    expose:
      - "3306"
    ports:
      - "3306:3306"
    networks:
      - local-network
    volumes:
      - "./setup/mysql:/docker-entrypoint-initdb.d:delegated"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  products:
    build: ./services/products
    expose:
      - "5001"
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
    depends_on:
      - mysql
    networks:
      - local-network
    volumes:
      - "./services/products:/app:cached"
      - "/app/node_modules"
    command: "supervisor -w ./ ./app.js"

  suppliers:
    build: ./services/suppliers
    expose:
      - "5003"
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=development
      - PORT=5003
    depends_on:
      - mongodb
    volumes:
      - "./services/suppliers:/app:cached"
      - "/app/node_modules"
    command: "supervisor -w ./ ./app.js"

  #clients:
  #  build: ./services/clients
  #  ports:
  #    - "5002:3000"
  #  environment:
  #    - NODE_ENV=development
  #  depends_on:
  #    - dynamodb-local

  #documents:
  #  build: ./services/documents
  #  ports:
  #    - "5004:3000"
  #  environment:
  #    - NODE_ENV=development
  #  depends_on:
  #    - localstack

  #dynamodb-local:
  #  image: amazon/dynamodb-local
  #  ports:
  #    - "8000:8000"

  #localstack:
  #  image: localstack/localstack
  #  environment:
  #    SERVICES: s3,sqs,sns,lambda,apigateway
  #  ports:
  #    - "4566:4566"
